name: First-time Contributor Check

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  greet-first-time-pr:
    name: Greet First-Time PR Contributors
    runs-on: ubuntu-latest
    steps:
      - name: Check for first-time PR contributor
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.actor;
            const { owner, repo } = context.repo;

            // NEUER ANSATZ: Liste alle Issues des Autors und filtere nach PRs.
            // Das ist zuverlässiger als die Suche.
            console.log(`Checking for past PRs from ${author}...`);
            const allIssues = await github.paginate(github.rest.issues.listForRepo, {
              owner,
              repo,
              creator: author,
              state: 'all'
            });

            const prs = allIssues.filter(issue => issue.pull_request);
            const prCount = prs.length;

            console.log(`Found ${prCount} PR(s) from ${author}.`);

            // Wenn es genau 1 PR gibt (nämlich diesen hier), dann poste den Kommentar
            if (prCount === 1) {
              console.log('This is the first PR. Posting a welcome comment.');
            
              const prMessage = `
              ### Hey @${author}! 🎉
            
              Thanks for opening your first pull request. We really appreciate it.
            
              👉 Please confirm by writing this comment that your contribution and following ones comply with the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0) and the [Code of Conduct](https://github.com/operaton/operaton/blob/main/CODE_OF_CONDUCT.md):
              \`\`\`
              I confirm that my contribution and following ones comply with the Apache License 2.0 and the Code of Conduct.
              \`\`\`
              Consider adding a star ⭐️ to the [repository](https://github.com/operaton/operaton) if you like it, we appreciate that.
            
              Contributors will be added to the release notes of the next release.
              `;

              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: context.issue.number,
                body: prMessage
              });
            } else {
              console.log('Not the first PR. Skipping comment.');
            }

  check-confirmation:
    name: Check Contributor Confirmation
    runs-on: ubuntu-latest
    # Wir führen diesen Job nur bei Kommentaren aus
    if: github.event_name == 'issue_comment'
    steps:
      - name: Check for confirmation comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const prAuthor = pr.user.login;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const confirmation = comments.find(c =>
              c.user.login === prAuthor &&
              c.body.toLowerCase().includes("i confirm that my contribution and following ones comply with the apache license 2.0 and the code of conduct.")
            );

            if (!confirmation) {
              core.setFailed("❌ The PR author has not confirmed the Apache License 2.0 contribution yet.");
            } else {
              core.info("✅ Confirmation found.");
            }